/*
Parametrizacion inicial
con varias tuplas por tabla
y uso de transacciones
No parametrizamos reservas porque es algo que hará cada usuario
*/

SHOW AUTOCOMMIT; --autocommit OFF

--Parametrizacion USERS
BEGIN
    INSERT INTO USERS(NAME, USERNAME, PASSWORD) VALUES ('Ada', 'adapiedrafita', 'ada1234');
    INSERT INTO USERS(NAME, USERNAME, PASSWORD) VALUES ('Administrador', 'admin', 'admin1234');
    INSERT INTO USERS(NAME, USERNAME, PASSWORD) VALUES ('Angel', 'angelladreroo', 'angel1234');
    INSERT INTO USERS(NAME, USERNAME, PASSWORD) VALUES ('Invitado', 'invitado', 'invitado1234');
    INSERT INTO USERS(NAME, USERNAME, PASSWORD) VALUES ('Sara', 'saragarcia', 'sara1234');
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ha habido un error en la transaccion:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('Van a deshacerse las inserciones de datos');
    ROLLBACK;
END;

--Parametrizacion DESTINATIONS
BEGIN
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Tailandia', 'Sudeste Asiatico', 9.2);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Mexico', 'Norteamerica', 9.0);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Jordania', 'Oriente Medio', 9.5);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Islandia', 'Europa', 8.8);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Tanzania', 'Africa', 9.8);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Peru', 'Sudamerica', 9.0);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Nueva York', 'Norteamerica', 8.2);
    INSERT INTO DESTINATIONS(NAME, AREA, SCORE) VALUES ('Marruecos', 'Africa', 8.6);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ha habido un error en la transaccion:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('Van a deshacerse las inserciones de datos');
    ROLLBACK;
END;


--Parametrizacion TRIPS
BEGIN
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (1, TO_DATE('01/05/2022', 'DD/MM/YYYY'), TO_DATE('16/05/2022', 'DD/MM/YYYY'), 1099.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (2, TO_DATE('01/05/2022', 'DD/MM/YYYY'), TO_DATE('16/05/2022', 'DD/MM/YYYY'), 1299.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (2, TO_DATE('01/06/2022', 'DD/MM/YYYY'), TO_DATE('16/06/2022', 'DD/MM/YYYY'), 1299.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (3, TO_DATE('01/05/2022', 'DD/MM/YYYY'), TO_DATE('08/05/2022', 'DD/MM/YYYY'), 799.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (3, TO_DATE('15/05/2022', 'DD/MM/YYYY'), TO_DATE('22/05/2022', 'DD/MM/YYYY'), 799.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (3, TO_DATE('03/06/2022', 'DD/MM/YYYY'), TO_DATE('10/06/2022', 'DD/MM/YYYY'), 799.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (4, TO_DATE('20/05/2022', 'DD/MM/YYYY'), TO_DATE('31/05/2022', 'DD/MM/YYYY'), 1199.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (5, TO_DATE('15/05/2022', 'DD/MM/YYYY'), TO_DATE('29/05/2022', 'DD/MM/YYYY'), 2899.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (6, TO_DATE('10/05/2022', 'DD/MM/YYYY'), TO_DATE('22/05/2022', 'DD/MM/YYYY'), 1399.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (6, TO_DATE('25/05/2022', 'DD/MM/YYYY'), TO_DATE('07/06/2022', 'DD/MM/YYYY'), 1399.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (8, TO_DATE('05/05/2022', 'DD/MM/YYYY'), TO_DATE('12/05/2022', 'DD/MM/YYYY'), 1099.99);
    INSERT INTO TRIPS(DESTINATION_ID, START_DATE, END_DATE, PRICE) VALUES (4, TO_DATE('20/06/2022', 'DD/MM/YYYY'), TO_DATE('01/07/2022', 'DD/MM/YYYY'), 699.99);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Ha habido un error en la transaccion:'||SQLERRM);
    DBMS_OUTPUT.PUT_LINE('Van a deshacerse las inserciones de datos');
    ROLLBACK;
END;
